apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: local
  namespace: devops-tools
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jenkins"